#
# This file is applied automatically by docker-compose
# see: https://docs.docker.com/compose/extends/
#
# This docker-compose is used to run everything in production setup on .localhost domain
#
# portainer:
#   # See README.md in portainer dir for more info on working with portainer
#   container_name: portainer.moonspeak.localhost
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock
#     # use anon volume during local dev
#     - /data
#   build:
#     context: ./portainer
#
# Important: you might need to define moonspeak.localhost in /etc/hosts 
#
# port definitions for services are for debug/development,
# except the gateway service which is expected to be exposed to the internet
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
version: "3"

volumes:
  # volume for demouser1
  userdata:
    name: userdata-demouser1

services:
  #===================================
  gateway:
    container_name: moonspeak.localhost
    build:
      context: ./gateway
    ports:
      - "80:8443"   # listens on 8433 to redirect to https port 443
      - "443:443"

  router:
    container_name: router.moonspeak.localhost
    build:
      context: ./router
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      # dev mode relaxes a number of restrictions (e.g. must have access to gateway's unix socket)
      MOONSPEAK_DEV_MODE: "1"
      RUST_LOG: "router=debug"

  manager:
    container_name: manager.moonspeak.localhost
    build:
      context: ./manager
    environment:
      # set debug to on
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      MOONSPEAK_DEPLOY_SECRET: "secret"
      PYTHON_ON_WHALES_DEBUG: "1"

  #===================================
  landing:
    container_name: landing.moonspeak.localhost
    build:
      context: ./landing

  synonyms:
    container_name: synonyms.moonspeak.localhost
    build:
      context: ./synonyms

  suggestions:
    container_name: suggestions.moonspeak.localhost
    build:
      context: ./suggestions

  #==================================
  # this is the demo user for development,  graph address is the user's unique access url
  workelements:
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    container_name: workelements-demouser1.moonspeak.localhost
    build:
      context: ./workelements
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
      - userdata:/opt/moonspeak/workelements/userdata
    networks:
      - moonspeaknet
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' --bind='unix:/opt/moonspeak/unixsocks/workelements-demouser1.sock' "

  graph:
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    container_name: graph-demouser1.moonspeak.localhost
    build:
      context: ./graph
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
      - userdata:/opt/moonspeak/graph/userdata
    networks:
      - moonspeaknet
    environment:
      MOONSPEAK_PORT: 80
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxfile host="localhost" modified="2022-12-04T06:11:18.071Z" agent="5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" etag="-J2dvMhjnH6SI7QTmTVN" version="@DRAWIO-VERSION@" type="moonspeak">
          <diagram id="SKebBaCcsGTVzdhOYIFn" name="pageWithNumber">
            <mxGraphModel dx="4075" dy="1171" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
              <root>
                <mxCell id="0" />
                <mxCell id="1" style="locked=1;" parent="0" />
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="/router/route/workelements-demouser1/" style="width: 680px; height: 560px; border: medium none;" id="2">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-210" y="-70" width="700" height="580" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/suggestions/" style="width: 380px; height: 290px; border: medium none;" id="4">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-790" y="-10" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/synonyms/" style="width: 340px; height: 530px; border: medium none;" id="5">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="580" y="-100" width="360" height="550" as="geometry" />
                  </mxCell>
                </iframe>
                <object label="freehand" id="JOpQ_ee-CrSYCSZTWhDq-18">
                  <mxCell style="" parent="0" />
                </object>
              </root>
            </mxGraphModel>
          </diagram>
        </mxfile>
