# Notes:
#
# port definitions for services are for debug/development, except the "80:80"
# for debug/development define moonspeak.test in /etc/hosts 
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
#
version: "3.9"

services:
  #===================================
  # this service name is not hardcoded
  gateway.moonspeak.test:
    image: ms-gateway:latest
    build:
      context: ./gateway-nginx
    ports:
      - "80:80"
    depends_on:
      - router.moonspeak.test

  router.moonspeak.test:
    image: ms-router:latest
    # the router inserts reference to hostname into each feature via <base> tag
    # this supplies the correct name
    env:
      MOONSPEAK_DOMAIN: "moonspeak.test"
    build:
      context: ./forwarder
    volumes:
      - /opt/ms/tmp

  #===================================
  login.moonspeak.test:
    image: ms-login:latest
    # the login creates new user services with names under the hostname domain
    # this supplies the correct domain name
    env:
      MOONSPEAK_DOMAIN: "moonspeak.test"
    build:
      context: ./login

  deploy.moonspeak.test:
    image: ms-deploy:latest
    # the deploy writes configuration for graph and hud services which have absolute urls
    # this supplies the correct domain and node names
    env:
    env:
      MOONSPEAK_DOMAIN: "moonspeak.test"
      MOONSPEAK_NODE: "node1"
    build:
      context: ./deploy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  landing.moonspeak.test:
    image: ms-landing:latest
    build:
      context: ./landing

  synonyms.moonspeak.test:
    image: ms-synonyms:latest
    build:
      context: ./synonyms
    volumes:
      - /opt/ms/tmp

  suggestions.moonspeak.test:
    image: ms-suggestions:latest
    build:
      context: ./suggestions
    volumes:
      - /opt/ms/tmp

  plugins.moonspeak.test:
    image: ms-plugins:latest
    build:
      context: ./plugins

  plus.moonspeak.test:
    image: ms-plus:latest
    build:
      context: ./plus

  help.moonspeak.test:
    image: ms-help:latest
    build:
      context: ./help

  #===================================
  # this is the user's unique access url
  hud-aaa.moonspeak.test:
    image: ms-hud:latest
    build:
      context: ./hud
    volumes:
      - /opt/ms/tmp
      - type: bind
        source: ./hud/tmp
        target: /opt/ms/tmp

  grapheditor-bbb.moonspeak.test:
    image: ms-grapheditor:latest
    build:
      context: ./grapheditor
    volumes:
      - /opt/ms/tmp

  submit-ccc.moonspeak.test:
    image: ms-submit:latest
    build:
      context: ./submit
    volumes:
      - /opt/ms/tmp

  workelements-ddd.moonspeak.test:
    image: ms-workelements:latest
    build:
      context: ./workelements
    volumes:
      - /opt/ms/tmp
