#
# This file is applied automatically by docker-compose
# see: https://docs.docker.com/compose/extends/
#
# This docker-compose is used to run everything in dev mode for .localhost domain
#
# Important: you might need to define moonspeak.localhost in /etc/hosts 
#
# port definitions for services are for debug/development,
# except the gateway service which is expected to be exposed to the internet
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.localhost
    build:
      context: ./gateway
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"

  router:
    container_name: router.moonspeak.localhost
    build:
      context: ./router
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      MOONSPEAK_DEV_MODE: "true"
      RUST_LOG: "router=info"

  #===================================
  landing:
    container_name: landing.moonspeak.localhost
    build:
      context: ./landing

  synonyms:
    container_name: synonyms.moonspeak.localhost
    build:
      context: ./synonyms
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' --bind='unix:/opt/moonspeak/unixsocks/synonyms.sock' "

  suggestions:
    container_name: suggestions.moonspeak.localhost
    build:
      context: ./suggestions

  # #==================================
  # this is the user's unique access url
  hud:
    image: "temachpool/moonspeak-hud:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    container_name: hud-demouser-aaa.moonspeak.localhost
    build:
      context: ./hud
    environment:
      MOONSPEAK_PORT: "80"
      MOONSPEAK_UNIXSOCK: "../unixsocks/hud-demouser-aaa.sock"
      MOONSPEAK_HUD_CONFIG_JSON: >-
          {
            "graphurl": "/router/node/graph-demouser-bbb"
          }

  workelements:
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
      - /opt/moonspeak/workelements/userdata
    container_name: workelements-demouser-ddd.moonspeak.localhost
    build:
      context: ./workelements
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' --bind='unix:/opt/moonspeak/unixsocks/workelements-demouser-ddd.sock' "

  graph:
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
      - /opt/moonspeak/graph/userdata
    container_name: graph-demouser-bbb.moonspeak.localhost
    build:
      context: ./graph
    environment:
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxGraphModel dx="2638" dy="1176" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100">
          <root>
            <mxCell id="0" />
            <mxCell id="1" parent="0" />
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="/router/node/workelements-demouser-ddd/" style="width: 680px; height: 560px; border: medium none;" id="2">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="-80" y="-85" width="700" height="580" as="geometry" />
              </mxCell>
            </iframe>
            <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
              <mxGeometry relative="1" as="geometry" />
            </mxCell>
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/suggestions/" style="width: 380px; height: 290px; border: medium none;" id="4">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="-530" y="-80" width="400" height="310" as="geometry" />
              </mxCell>
            </iframe>
            <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
              <mxGeometry relative="1" as="geometry" />
            </mxCell>
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/synonyms/" style="width: 340px; height: 530px; border: medium none;" id="5">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="650" y="-70" width="360" height="550" as="geometry" />
              </mxCell>
            </iframe>
          </root>
        </mxGraphModel>
