version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.test
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"

  router:
    container_name: router.moonspeak.test
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.test"

  #===================================
  landing:
    container_name: landing.moonspeak.test
