# Notes:
#
# port definitions for services are for debug/development, except the "80:80"
# for debug/development define moonspeak.test in /etc/hosts 
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
# On having both IMAGE and BUILD per service: https://docs.docker.com/compose/compose-file/build/#consistency-with-image
#
version: "3"

services:
  #===================================
  gateway:
    image: temachpool/moonspeak-gateway:latest

  forwarder:
    image: temachpool/moonspeak-router:latest
    environment:
      # the router inserts reference to hostname into each feature via <base> tag
      # this supplies the correct name
      MOONSPEAK_DOMAIN: "moonspeak.test"

  #===================================
  landing:
    image: temachpool/moonspeak-landing:latest

  # synonyms:
  #   container_name: synonyms.moonspeak.test
  #   image: moonspeak-synonyms:latest
  #   build:
  #     context: ./synonyms
  #   volumes:
  #     - /opt/ms/tmp

  # suggestions.moonspeak.test:
  #   image: moonspeak-suggestions:latest
  #   build:
  #     context: ./suggestions
  #   volumes:
  #     - /opt/ms/tmp

  # plugins.moonspeak.test:
  #   image: moonspeak-plugins:latest
  #   build:
  #     context: ./plugins

  # plus.moonspeak.test:
  #   image: moonspeak-plus:latest
  #   build:
  #     context: ./plus

  # help.moonspeak.test:
  #   image: moonspeak-help:latest
  #   build:
  #     context: ./help

  #===================================
  # this is the user's unique access url
  # hud-demouser-aaa.moonspeak.test:
  #   image: moonspeak-hud:latest
  #   build:
  #     context: ./hud
  #   environment:
  #     # this json lists urls that hud should load for the user
  #     MOONSPEAK_HUD_CONFIG_JSON:  "{\"urls\":[\"/plus/\",\"/router/localhost/graph-demouser-bbb\"]}"
  #   volumes:
  #     - /opt/ms/tmp

  # graph-demouser-bbb.moonspeak.test:
  #   image: moonspeak-graph:latest
  #   build:
  #     context: ./grapheditor
  #   environment:
  #     # this xml sets default graph value
  #     MOONSPEAK_GRAPH_INITIAL_XML: "<mxGraphModel><root><mxCell id=\"0\"/><mxCell id=\"1\" parent=\"0\"/></root></mxGraphModel>"
  #   volumes:
  #     - /opt/ms/tmp

  # submit-demouser-ccc.moonspeak.test:
  #   image: moonspeak-submit:latest
  #   build:
  #     context: ./submit
  #   volumes:
  #     - /opt/ms/tmp

  # workelements-demouser-ddd.moonspeak.test:
  #   image: moonspeak-workelements:latest
  #   build:
  #     context: ./workelements
  #   volumes:
  #     - /opt/ms/tmp

  #===================================
  # Deploy is used in manual mode, see its source
  # deploy.moonspeak.test:
  #   image: moonspeak-deploy:latest
  #   environment:
  #     # the deploy writes configuration for graph and hud services which have absolute urls
  #     # this supplies the correct domain
  #     MOONSPEAK_DOMAIN: "moonspeak.test"
  #     MOONSPEAK_DEPLOY_SECRET: "my_secret"
  #   build:
  #     context: ./deploy
  #   ports:
  #     - "127.0.0.20:80:80"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

