#
# ALSO MUST SEE ./docker-compose.override.yml
#
version: "3"

volumes:
  # used to share unix sockets
  unixsocks:

services:
  #===================================
  gateway:
    image: "temachpool/moonspeak-gateway:${TAG:-latest}"
    volumes:
      - unixsocks:/etc/unixsocks

  router:
    image: "temachpool/moonspeak-router:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    environment:
      # the router inserts reference to hostname into each feature via <base> tag
      # this supplies the correct name
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      # turn off debug features
      MOONSPEAK_DEV_MODE: ""
      RUST_LOG: "router=info"

  #===================================
  landing:
    image: "temachpool/moonspeak-landing:${TAG:-latest}"
    volumes:
      - unixsocks:/etc/unixsocks

  synonyms:
    image: "temachpool/moonspeak-synonyms:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' --bind='unix:/opt/moonspeak/unixsocks/synonyms.sock' "

  suggestions:
    image: "temachpool/moonspeak-suggestions:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    environment:
      MOONSPEAK_PORT: 80

  # #==================================
  # this is the demo stand on production
  hud:
    image: "temachpool/moonspeak-hud:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    environment:
      MOONSPEAK_PORT: "80"
      MOONSPEAK_UNIXSOCK: "../unixsocks/hud-demouser-aaa.sock"
      MOONSPEAK_HUD_CONFIG_JSON: >-
          {
            "graphurl": "/router/route/graph-demouser-bbb/index.html"
          }

  workelements:
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
      - /opt/moonspeak/workelements/userdata
    environment:
      GUNICORN_CMD_ARGS: " --bind='0.0.0.0:80' --bind='unix:/opt/moonspeak/unixsocks/workelements-demouser-ddd.sock' "

  graph:
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
      - /opt/moonspeak/graph/userdata
    environment:
      MOONSPEAK_PORT: 80
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxGraphModel dx="2638" dy="1176" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100">
          <root>
            <mxCell id="0" />
            <mxCell id="1" parent="0" />
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/synonyms/" style="width: 680px; height: 560px; border: medium none;" id="2">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="-80" y="-85" width="700" height="580" as="geometry" />
              </mxCell>
            </iframe>
            <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
              <mxGeometry relative="1" as="geometry" />
            </mxCell>
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/suggestions/" style="width: 380px; height: 290px; border: medium none;" id="4">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="-530" y="-80" width="400" height="310" as="geometry" />
              </mxCell>
            </iframe>
          </root>
        </mxGraphModel>

  #===================================
  # Deploy is used in manual mode, see its source
  # deploy.moonspeak.localhost:
  #   image: moonspeak-deploy:latest
  #   environment:
  #     # the deploy writes configuration for graph and hud services which have absolute urls
  #     # this supplies the correct domain
  #     MOONSPEAK_DOMAIN: "moonspeak.localhost"
  #     MOONSPEAK_DEPLOY_SECRET: "my_secret"
  #   build:
  #     context: ./deploy
  #   ports:
  #     - "127.0.0.20:80:80"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
