# Notes:
#
# port definitions for services are for debug/development, except the "80:80"
# for debug/development define moonspeak.test in /etc/hosts 
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
#
version: "3.9"

networks:
  moonspeak-static:
    name: moonspeak-static
  moonspeak-dynamic:
    name: moonspeak-dynamic

services:
  #===================================
  # this service name is not hardcoded
  gateway.moonspeak.test:
    image: ms-gateway:latest
    build:
      context: ./gateway-nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    networks:
      - moonspeak-static
    depends_on:
      - router.moonspeak.test

  router.moonspeak.test:
    image: ms-router:latest
    hostname: moonspeak.test
    build:
      context: ./forwarder
      dockerfile: Dockerfile
    ports:
      - "9001:80"
    volumes:
      - /opt/ms/tmp
    networks:
      - moonspeak-static
      - moonspeak-dynamic

  #===================================
  landing.moonspeak.test:
    image: ms-landing:latest
    build:
      context: ./landing
      dockerfile: Dockerfile
    ports:
      - "9010:80"
    networks:
      - moonspeak-static

  synonyms.moonspeak.test:
    image: ms-synonyms:latest
    build:
      context: ./synonyms
      dockerfile: Dockerfile
    volumes:
      - /opt/ms/tmp
    ports:
      - "9011:80"
    networks:
      - moonspeak-static

  suggestions.moonspeak.test:
    image: ms-suggestions:latest
    build:
      context: ./suggestions
      dockerfile: Dockerfile
    volumes:
      - /opt/ms/tmp
    ports:
      - "9012:80"
    networks:
      - moonspeak-static

  plugins.moonspeak.test:
    image: ms-plugins:latest
    build:
      context: ./plugins
      dockerfile: Dockerfile
    ports:
      - "9013:80"
    networks:
      - moonspeak-static

  plus.moonspeak.test:
    image: ms-plus:latest
    build:
      context: ./plus
      dockerfile: Dockerfile-backend
    ports:
      - "9014:80"
    networks:
      - moonspeak-static

  #===================================
  # this is the user's unique access url
  hud-aaa.moonspeak.test:
    image: ms-hud:latest
    build:
      context: ./hud
      dockerfile: Dockerfile-backend
    volumes:
      - /opt/ms/tmp
      - type: bind
        source: ./hud/tmp
        target: /opt/ms/tmp
    networks:
      - moonspeak-dynamic


  grapheditor-bbb.moonspeak.test:
    image: ms-grapheditor:latest
    build:
      context: ./grapheditor
      dockerfile: Dockerfile-backend 
    volumes:
      - /opt/ms/tmp
    networks:
      - moonspeak-dynamic

  submit-ccc.moonspeak.test:
    image: ms-submit:latest
    build:
      context: ./submit
      dockerfile: Dockerfile-backend 
    volumes:
      - /opt/ms/tmp
    networks:
      - moonspeak-dynamic

  workelements-ddd.moonspeak.test:
    image: ms-workelements:latest
    build:
      context: ./workelements
      dockerfile: Dockerfile-backend 
    volumes:
      - /opt/ms/tmp
    networks:
      - moonspeak-dynamic
