# This file is applied automatically by docker-compose
# see: https://docs.docker.com/compose/extends/
#
#
# port definitions for services are for debug/development, except the gateway service 
# which is exposed to the internet
#
#
# for debug/development define moonspeak.test in /etc/hosts 
#
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
#
# On having both IMAGE and BUILD per service: https://docs.docker.com/compose/compose-file/build/#consistency-with-image
#
#
version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.test
    build:
      context: ./gateway-nginx
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"

  router:
    container_name: router.moonspeak.test
    build:
      context: ./router
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.test"
      MOONSPEAK_DEV_MODE: "true"
      RUST_LOG: "router=info"
    ports:
        - "127.0.0.1:8000:80"

  #===================================
  landing:
    container_name: landing.moonspeak.test
    build:
      context: ./landing

  #===================================
  # Services for dev mode only
  # "{\"services\":[{\"service_name\":\"workelements\",\"service_url\":\"/router/node/workelements-demouser-ddd\",\"image_url\":\"static/images/icons48/table.png\"},{\"service_name\":\"synonyms\",\"service_url\":\"/synonyms\",\"image_url\":\"static/images/icons48/earth.png\"},{\"service_name\":\"suggestions\",\"service_url\":\"/suggestions\",\"image_url\":\"static/images/icons48/gear.png\"},{\"service_name\":\"submit\",\"service_url\":\"/router/node/submit-demouser-ccc\",\"image_url\":\"static/images/icons48/keys.png\"}]}"
  plus:
    container_name: plus.moonspeak.test
    build:
      context: ./plus
    # docker-compose on server is old and ignores "configs", so we dance around with env + echo
    # command: echo "$MOONSPEAK_PLUS_CONFIG_JSON" > /etc/nginx/frontend/config/plus.json && nginx -g "daemon off;"
    environment:
      MOONSPEAK_PLUS_CONFIG_JSON:  >- 
          {
              "services": [
                  {
                      "name": "synonyms",
                      "url": "/synonyms"
                  },
                  {
                      "name": "suggestions",
                      "url": "/suggestions"
                  },
                  {
                      "name": "workelements",
                      "url": "/router/node/workelements-demouser-ddd"
                  },
                  {
                      "name": "submit",
                      "url": "/router/node/submit-demouser-ccc"
                  }
              ]
          }

  #===================================
  # this is the user's unique access url
  hud-demo:
    container_name: hud-demouser-aaa.moonspeak.test
    image: moonspeak-hud:latest
    build:
      context: ./hud
    volumes:
      - /opt/ms/tmp
    # docker-compose on server is old and ignores "configs", so we dance around with env + echo
    # command: echo "$MOONSPEAK_HUD_CONFIG_JSON" > /etc/nginx/frontend/config/hud.json && nginx -g "daemon off;"
    environment:
      # this json lists urls that hud should load for the user
      MOONSPEAK_HUD_CONFIG_JSON: >-
          {
            "urls": [
              "/plus/",
              "/router/node/graph-demouser-bbb"
            ]
          }

  # "<mxGraphModel><root><mxCell id=\"0\"/><mxCell id=\"1\" parent=\"0\"/><iframe xmlns=\"http://www.w3.org/1999/xhtml\" src=\"http://moonspeak.test:8040\" id=\"2\"><mxCell xmlns=\"\" style=\"iframe=1;\" vertex=\"1\" parent=\"1\"><mxGeometry x=\"320\" y=\"310\" width=\"320\" height=\"170\" as=\"geometry\"/></mxCell></iframe><iframe xmlns=\"http://www.w3.org/1999/xhtml\" src=\"http://moonspeak.test:8041\" id=\"3\"><mxCell xmlns=\"\" style=\"iframe=1;\" vertex=\"1\" parent=\"1\"><mxGeometry x=\"820\" y=\"400\" width=\"320\" height=\"170\" as=\"geometry\"/></mxCell></iframe><iframe xmlns=\"http://www.w3.org/1999/xhtml\" src=\"http://moonspeak.test:8042\" id=\"4\"><mxCell xmlns=\"\" style=\"iframe=1;\" vertex=\"1\" parent=\"1\"><mxGeometry x=\"1010\" y=\"130\" width=\"320\" height=\"170\" as=\"geometry\"/></mxCell></iframe><iframe xmlns=\"http://www.w3.org/1999/xhtml\" src=\"http://moonspeak.test:8043\" id=\"5\"><mxCell xmlns=\"\" style=\"iframe=1;\" vertex=\"1\" parent=\"1\"><mxGeometry x=\"540\" y=\"10\" width=\"320\" height=\"170\" as=\"geometry\"/></mxCell></iframe></root></mxGraphModel>"
  graph-demo:
    container_name: graph-demouser-bbb.moonspeak.test
    image: moonspeak-graph:latest
    build:
      context: ./grapheditor
    volumes:
      - /opt/ms/tmp
    environment:
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
              <mxGraphModel>
                  <root>
                      <mxCell id="0"/>
                      <mxCell id="1" parent="0"/>
                      <iframe
                          xmlns="http://www.w3.org/1999/xhtml" src="http://moonspeak.test:8040" id="2">
                          <mxCell
                              xmlns="" style="iframe=1;" vertex="1" parent="1">
                              <mxGeometry x="320" y="310" width="320" height="170" as="geometry"/>
                          </mxCell>
                      </iframe>
                      <iframe
                          xmlns="http://www.w3.org/1999/xhtml" src="http://moonspeak.test:8041" id="3">
                          <mxCell
                              xmlns="" style="iframe=1;" vertex="1" parent="1">
                              <mxGeometry x="820" y="400" width="320" height="170" as="geometry"/>
                          </mxCell>
                      </iframe>
                      <iframe
                          xmlns="http://www.w3.org/1999/xhtml" src="http://moonspeak.test:8042" id="4">
                          <mxCell
                              xmlns="" style="iframe=1;" vertex="1" parent="1">
                              <mxGeometry x="1010" y="130" width="320" height="170" as="geometry"/>
                          </mxCell>
                      </iframe>
                      <iframe
                          xmlns="http://www.w3.org/1999/xhtml" src="http://moonspeak.test:8043" id="5">
                          <mxCell
                              xmlns="" style="iframe=1;" vertex="1" parent="1">
                              <mxGeometry x="540" y="10" width="320" height="170" as="geometry"/>
                          </mxCell>
                      </iframe>
                  </root>
              </mxGraphModel>

  # submit-demouser-ccc.moonspeak.test:
  #   image: moonspeak-submit:latest
  #   build:
  #     context: ./submit
  #   volumes:
  #     - /opt/ms/tmp

  # workelements-demouser-ddd.moonspeak.test:
  #   image: moonspeak-workelements:latest
  #   build:
  #     context: ./workelements
  #   volumes:
  #     - /opt/ms/tmp
