version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.ru
    restart: always
    volumes:
      - type: bind
        source: /etc/letsencrypt/live/moonspeak.ru/fullchain.pem
        target: /moonspeak/fullchain.pem
      - type: bind
        source: /etc/letsencrypt/live/moonspeak.ru/privkey.pem
        target: /moonspeak/privkey.pem
    ports:
      - "443:443"

  forwarder:
    container_name: router.moonspeak.ru
    restart: always
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.ru"

  #===================================
  landing:
    container_name: landing.moonspeak.ru
    restart: always

