#
# ALSO MUST SEE ./docker-compose.override.yml
#
version: "3"

volumes:
  # used to share unix sockets
  unixsocks:

services:
  #===================================
  gateway:
    image: "temachpool/moonspeak-gateway:${TAG:-latest}"
    volumes:
      - unixsocks:/etc/unixsocks

  router:
    image: "temachpool/moonspeak-router:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks
    environment:
      # the router inserts reference to hostname into each feature via <base> tag
      # this supplies the correct name
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      # turn off debug features
      MOONSPEAK_DEV_MODE: ""
      RUST_LOG: "router=info"

  #===================================
  landing:
    image: "temachpool/moonspeak-landing:${TAG:-latest}"
    volumes:
      - unixsocks:/etc/unixsocks

  synonyms:
    image: "temachpool/moonspeak-synonyms:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks

  suggestions:
    image: "temachpool/moonspeak-suggestions:${TAG:-latest}"
    volumes:
      - unixsocks:/opt/moonspeak/unixsocks

  #===================================
  # Deploy is used in manual mode, see its source
  # deploy.moonspeak.localhost:
  #   image: moonspeak-deploy:latest
  #   environment:
  #     # the deploy writes configuration for graph and hud services which have absolute urls
  #     # this supplies the correct domain
  #     MOONSPEAK_DOMAIN: "moonspeak.localhost"
  #     MOONSPEAK_DEPLOY_SECRET: "my_secret"
  #   build:
  #     context: ./deploy
  #   ports:
  #     - "127.0.0.20:80:80"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
