#
# This file is applied automatically by docker-compose
# see: https://docs.docker.com/compose/extends/
#
# This docker-compose is used to run everything in production setup on .localhost domain
#
# Important: you might need to define moonspeak.localhost in /etc/hosts 
#
# port definitions for services are for debug/development,
# except the gateway service which is expected to be exposed to the internet
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.localhost
    build:
      context: ./gateway
    ports:
      - "80:8443"   # listens on 8433 to redirect to https port 443
      - "443:443"

  router:
    container_name: router.moonspeak.localhost
    build:
      context: ./router
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.localhost"
      MOONSPEAK_DEV_MODE: ""
      RUST_LOG: "router=debug"

  #===================================
  landing:
    container_name: landing.moonspeak.localhost
    build:
      context: ./landing

  synonyms:
    container_name: synonyms.moonspeak.localhost
    build:
      context: ./synonyms

  suggestions:
    container_name: suggestions.moonspeak.localhost
    build:
      context: ./suggestions

  # #==================================
  # graph address is the user's unique access url
  workelements:
    container_name: workelements-demouser-ddd.moonspeak.localhost
    build:
      context: ./workelements

  graph:
    container_name: graph-demouser-bbb.moonspeak.localhost
    build:
      context: ./graph
