version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.ru
    restart: always
    volumes:
      - "/etc/letsencrypt/live/moonspeak.ru/fullchain.pem:/etc/nginx/fullchain.pem:ro"
      - "/etc/letsencrypt/live/moonspeak.ru/privkey.pem:/etc/nginx/privkey.pem:ro"
    ports:
      - "80:80"
      - "443:443"

  router:
    container_name: router.moonspeak.ru
    restart: always
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.ru"

  #===================================
  landing:
    container_name: landing.moonspeak.ru
    restart: always

