version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.test
    build:
      context: ./gateway-nginx
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:80"

  router:
    container_name: router.moonspeak.test
    build:
      context: ./router
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.test"
      MOONSPEAK_DEV_MODE: "true"
      RUST_LOG: "router=info"

  #===================================
  landing:
    container_name: landing.moonspeak.test
    build:
      context: ./landing
