#
# This docker-compose is used to run everything in dev mode for .test domain
#
# port definitions for services are for debug/development, except the gateway service 
# which gets exposed to the internet
#
# Important: define moonspeak.test in /etc/hosts 
#
# For pdb debug add to service definition:
#   stdin_open: true  # docker run -i
#   tty: true         # docker run -t
# and run "docker attach CONTAINER_NAME"
#
version: "3"

services:
  #===================================
  gateway:
    container_name: moonspeak.test
    build:
      context: ./gateway-nginx
    ports:
      - "127.0.0.1:8443:8443"
      - "127.0.0.1:443:443"
      - "127.0.0.1:80:8443"

  router:
    container_name: router.moonspeak.test
    build:
      context: ./router
    environment:
      MOONSPEAK_DOMAIN: "moonspeak.test"
      MOONSPEAK_DEV_MODE: "true"
      RUST_LOG: "router=info"
    ports:
        - "127.0.0.1:8000:80"

  #===================================
  landing:
    container_name: landing.moonspeak.test
    build:
      context: ./landing

  synonyms:
    container_name: synonyms.moonspeak.test
    build:
      context: ./synonyms

  suggestions:
    container_name: suggestions.moonspeak.test
    build:
      context: ./suggestions

  #==================================
  # this is the user's unique access url
  hud:
    container_name: hud-demouser-aaa.moonspeak.test
    image: "temachpool/moonspeak-hud:${TAG:-latest}"
    build:
      context: ./hud
    volumes:
      - /opt/ms/tmp
    environment:
      # this json lists urls that hud should load for the user
      MOONSPEAK_HUD_CONFIG_JSON: >-
          {
            "graphurl": "/router/node/graph-demouser-bbb",
            "services": [
                {
                    "name": "synonyms",
                    "url": "/synonyms"
                },
                {
                    "name": "suggestions",
                    "url": "/suggestions"
                },
                {
                    "name": "workelements",
                    "url": "/router/node/workelements-demouser-ddd"
                }
            ]
          }

  submit:
    container_name: submit-demouser-ccc.moonspeak.test
    image: "temachpool/moonspeak-submit:${TAG:-latest}"
    build:
      context: ./submit
    volumes:
      - /opt/ms/tmp

  workelements:
    container_name: workelements-demouser-ddd.moonspeak.test
    image: "temachpool/moonspeak-workelements:${TAG:-latest}"
    build:
      context: ./workelements
    volumes:
      - /opt/ms/tmp

  graph:
    container_name: graph-demouser-bbb.moonspeak.test
    image: "temachpool/moonspeak-graph:${TAG:-latest}"
    build:
      context: ./grapheditor
    volumes:
      - /opt/ms/tmp
    environment:
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxGraphModel dx="3474" dy="1551" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100">
          <root>
            <mxCell id="0" />
            <mxCell id="1" parent="0" />
            <mxCell id="8" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.625;entryY=1;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="2" target="4" edge="1">
              <mxGeometry relative="1" as="geometry" />
            </mxCell>
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="/router/node/workelements-demouser-ddd" style="width: 680px; height: 560px; border: medium none;" id="2">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="-70" y="130" width="700" height="580" as="geometry" />
              </mxCell>
            </iframe>
            <mxCell id="9" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="3" target="5" edge="1">
              <mxGeometry relative="1" as="geometry" />
            </mxCell>
            <mxCell id="10" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="3" target="2" edge="1">
              <mxGeometry relative="1" as="geometry" />
            </mxCell>
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="submit" src="/router/node/submit-demouser-ccc" style="width: 660px; height: 110px; border: medium none;" id="3">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="-60" y="-30" width="680" height="130" as="geometry" />
              </mxCell>
            </iframe>
            <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="4" target="3" edge="1">
              <mxGeometry relative="1" as="geometry" />
            </mxCell>
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="/suggestions" style="width: 380px; height: 290px; border: medium none;" id="4">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="-510" y="-40" width="400" height="310" as="geometry" />
              </mxCell>
            </iframe>
            <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="/synonyms" style="width: 360px; height: 410px; border: medium none;" id="5">
              <mxCell xmlns="" style="iframe=1;" parent="1" vertex="1">
                <mxGeometry x="660" y="-100" width="380" height="430" as="geometry" />
              </mxCell>
            </iframe>
          </root>
        </mxGraphModel>

