#
# using env variables in compose file, see: https://docs.docker.com/compose/environment-variables/env-file/#parameter-expansion
#

version: "3"

services:
  workelements:
    # if devmode user count is 1, will give port mapping like "12000:80"
    ports:
      - "${MOONSPEAK_DEVMODE_COUNT:?You must set MOONSPEAK_DEVMODE_COUNT env var, e.g. MOONSPEAK_DEVMODE_COUNT=1}0002:80"

  graph:
    # if devmode user count is 1, will give port mapping like "12000:80"
    ports:
      - "${MOONSPEAK_DEVMODE_COUNT}0001:80"
    environment:
      # this xml sets default graph value
      MOONSPEAK_GRAPH_INITIAL_XML: >-
        <mxfile host="localhost" modified="2022-12-04T06:11:18.071Z" agent="5.0 (Windows NT 6.2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.54 Safari/537.36" etag="-J2dvMhjnH6SI7QTmTVN" version="@DRAWIO-VERSION@" type="moonspeak">
          <diagram id="SKebBaCcsGTVzdhOYIFn" name="pageWithNumber">
            <mxGraphModel dx="4075" dy="1171" grid="1" gridSize="10" guides="1" tooltips="0" connect="1" arrows="1" fold="1" page="0" pageScale="1" pageWidth="850" pageHeight="1100" math="0" shadow="0">
              <root>
                <mxCell id="0" />
                <mxCell id="1" style="locked=1;" parent="0" />
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="workelements" src="http://moonspeak.localhost:${MOONSPEAK_DEVMODE_COUNT}0002" style="width: 680px; height: 560px; border: medium none;" id="2">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-210" y="-70" width="700" height="580" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="11" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;entryX=0.003;entryY=0.384;entryDx=0;entryDy=0;entryPerimeter=0;" parent="1" source="4" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="suggestions" src="http://moonspeak.localhost:8081" style="width: 380px; height: 290px; border: medium none;" id="4">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="-790" y="-10" width="400" height="310" as="geometry" />
                  </mxCell>
                </iframe>
                <mxCell id="12" style="edgeStyle=orthogonalEdgeStyle;rounded=1;orthogonalLoop=1;jettySize=auto;html=1;" parent="1" source="5" target="2" edge="1">
                  <mxGeometry relative="1" as="geometry" />
                </mxCell>
                <iframe xmlns="http://www.w3.org/1999/xhtml" name="synonyms" src="http://moonspeak.localhost:8082" style="width: 340px; height: 530px; border: medium none;" id="5">
                  <mxCell style="iframe=1;" parent="1" xmlns="" vertex="1">
                    <mxGeometry x="580" y="-100" width="360" height="550" as="geometry" />
                  </mxCell>
                </iframe>
                <object label="freehand" id="JOpQ_ee-CrSYCSZTWhDq-18">
                  <mxCell style="" parent="0" />
                </object>
              </root>
            </mxGraphModel>
          </diagram>
        </mxfile>
