# docker-in-docker and buildah/kaniko: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html
#
# podman is based on buildah. Both need unshare permission, see: https://github.com/containers/buildah/issues/1901
# kaniko is the actual rootless builder, but does not support compose spec.
# In the end use docker with socket binding: https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#use-the-docker-executor-with-docker-socket-binding

build-docker-images:
  image: docker:latest
  stage: build
  variables:
    # the docker:latest image sets this by default to DOCKER_HOST=tcp://docker:2375
    DOCKER_HOST: "unix:///var/run/docker.sock"
  rules:
    - if: $CI_COMMIT_BRANCH == "latest" || $CI_COMMIT_BRANCH =~ /^2023/
  script:
    # remember that password with special characters may need to be escaped, i.e. '&pass!word' -> '\&pass\!word'
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" docker.io
    - ( cd moonspeak && TAG="$CI_COMMIT_BRANCH" docker compose build )
    - ( cd moonspeak && TAG="$CI_COMMIT_BRANCH" docker compose push )
    - docker logout

