# see: https://itnext.io/go-continuous-integration-with-travis-ci-and-docker-4b26379e54b7
# see: https://docs.travis-ci.com/user/docker/
#
stages:
  - build-push-latest

cache:
  directories:
  - docker_images

before_install:
- docker load -i docker_images/images.tar || true

before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)

jobs:
  include:
    # push docker image
    - stage: build-push-latest
      if: branch = master
      services:
        - docker
      install:
        - ( cd moonspeak && TAG="latest" docker-compose build )
      script: 
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - ( cd moonspeak && TAG="latest" docker-compose push )
        - docker logout
