# see: https://itnext.io/go-continuous-integration-with-travis-ci-and-docker-4b26379e54b7
# see: https://docs.travis-ci.com/user/docker/
#
stages:
  - build-push-latest

jobs:
  include:
    # push docker image
    - stage: build-push-latest
      if: branch = master
      services:
        - docker
      install:
        - ( cd moonspeak && TAG="2022-12-06" docker-compose build )
      script: 
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - ( cd moonspeak && TAG="2022-12-06" docker-compose push )
        - docker logout
