# see: https://itnext.io/go-continuous-integration-with-travis-ci-and-docker-4b26379e54b7
# see: https://docs.travis-ci.com/user/docker/


# faster startup time
# failed when trying to use LXD containers, they are beta and have bugs e.g. old version of docker
# language minimal or generic see: https://docs.travis-ci.com/user/languages/minimal-and-generic/
language: minimal

stages:
  - build-push-latest

cache:
  directories:
  - docker_images

before_install:
- docker load -i docker_images/images.tar || true

before_cache:
# keep cache smaller by dropping redundant images
- docker image prune --force
- docker save -o docker_images/images.tar $(docker images -a -q)

jobs:
  include:
    - stage: build-push-latest
      if: branch = latest OR branch =~ ^2023
      services:
        - docker
      script:
        - ( cd moonspeak && TAG="$TRAVIS_BRANCH" docker-compose build )
        # remember that password with special characters must be escaped, i.e. '&pass!word' -> '\&pass\!word' in travis web gui
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
        - ( cd moonspeak && TAG="$TRAVIS_BRANCH" docker-compose push )
        - docker logout
