# see: https://itnext.io/go-continuous-integration-with-travis-ci-and-docker-4b26379e54b7
# see: https://docs.travis-ci.com/user/docker/
#
stages:
  - build-push-latest

cache:
  directories:
  - docker_images

before_install:
- docker load -i docker_images/images.tar || true

before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)

jobs:
  include:
    # push docker image
    - stage: build-push-latest
      if: branch = master
      services:
        - docker
      install:
        - ( cd moonspeak && TAG="latest" docker-compose build )
      script: 
        # remember that password with special characters must be escaped, i.e. '&pass!word' -> '\&pass\!word' in travis web gui
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - ( cd moonspeak && TAG="latest" docker-compose push )
        - docker logout

    - stage: build-push-tag
      if: (branch = master) AND (tag =~ ^2023 )
      services:
        - docker
      install:
        - ( cd moonspeak && TAG="$TRAVIS_TAG" docker-compose build )
      script:
        # remember that password with special characters must be escaped, i.e. '&pass!word' -> '\&pass\!word' in travis web gui
        - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        - ( cd moonspeak && TAG="$TRAVIS_TAG" docker-compose push )
        - docker logout
