title = """Moonspeak - победим иероглифы"""
menu__item__index_html = """Главная"""
menu__item__documentation = """Документация"""
hero__title = """Скоро полноценный запуск!"""

hero__description = """
Сейчас мунспик в закрытом тестировании, подписывайтесь на телеграм канал чтобы узнать о запуске <a href="https://t.me/moonspeak_ru" target="_blank" class="link link--light">@moonspeak_ru</a>
"""

footer = """
Мунспик это открытый проект, участвуй в его разработке на <a href="https://github.com/temach/jplang" target="_blank" class="link link--light">Github</a>.
"""

