title = """Moonspeak - learn kanji"""
menu__item__index_html = """Home"""
menu__item__documentation = """Documentation"""
hero__title = """Launching soon!"""

hero__description = """
We are in closed beta testing right now, follow us on Telegram for updates <a class="link link--light" href="https://t.me/moonspeak_uk" target="_blank">@moonspeak_uk</a>.
"""

footer = """
Moonspeak is open source, help with development on <a class="link link--light" href="https://github.com/temach/jplang" target="_blank">Github</a>.
"""
