title = "Moonspeak Документация"
logo = """Moonspeak <span class="logo__thin">Доки</span>"""
menu__item__index_html = """Главная"""

doc__nav__intro = "Введение"
doc__nav__project = "Проект"
doc__nav__dev = "Разработка"
doc__nav__feedback = "Обратная связь"

doc__introduction__title = """Введение"""
doc__introduction__html = """
<h5>Итак, вы решили выучить кандзи.</h5>

<p>Что ж, прежде чем вы вступите в ряды людей, посвятивших свою жизнь изучению этой таинственной формы общения, было бы полезно сделать шаг назад и сделать обзор всего процесса. Можно сказать что есть 3 этапа изучения кандзи.</p>

<h5>Этап 1: Выучите отдельные иероглифы</h5>

<p>Ну, там всего <a class="link link--light" href="https://ru.wikipedia.org/wiki/%D0%94%D0%B7%D1%91%D1%91_%D0%BA%D0%B0%D0%BD%D0%B4%D0%B7%D0%B8" target="_blank">2136 иероглифов джойо</a>, насколько же это может быть сложно? Хорошо. На протяжении многих лет люди предлагали множество различных способов их изучения. Изучайте только значения и забудьте показания (метод Хейзига). Изучайте их в контексте слов, записывайте их, не записывайте их, создавайте мнемонику, превращайте их в забавные картинки, разбирайте их на составные части. Каким-то образом вам нужно будет найти способ поместить их в свой мозг.</p>

<h5>Этап 2: Выучите сложные иероглифы и слова</h5>

<p>Отдельные иероглифы ограничены в своей полезности. Только когда вы начинаете создавать с их помощью слова и предложения, они начинают приобретать истинное значение. Примерно в это же время японская система письма начинает казаться либо бесконечно увлекательной, либо просто глупой, в зависимости от того, как вы на это смотрите. Например, 気 означает “небеса”, а 気 - “дух”. Но когда вы складываете их вместе, они означают “погода”. Вам, вероятно, будет трудно догадаться, что небеса + дух = погода, но, по крайней мере, вы сможете извлечь из этого какой-то смысл, как только узнаете, даже если это будет натяжкой.</p>
<p>К сожалению, многое в японском языке даже не так понятно. Давайте посмотрим, как вы поступите с еще одним примером: 気, что означает “дух” + 象, что означает “слон” или “явление”. Так что же означает 気象? Подсказка: это не означает дух мертвого слона. И вот в чем проблема. </p>
<p>Даже если вы в совершенстве знаете все 2136 иероглифов, вы все равно не сможете читать по-японски. Потому что чтение японского языка требует не только знания всех отдельных иероглифов, но и четкого понимания того, как они используются в сочетании для образования слов, а число этих слов исчисляется десятками тысяч. Другими словами, это более серьезная проблема, чем кажется на первый взгляд.</p>

<h5>Этап 3: Чтение в контексте</h5>

<p>Теперь позвольте мне бросить вам еще один вызов. (О, и, кстати, 気象 также означает "погода”. Не спрашивай почему.) Последняя задача - прочитать иероглифы в контексте. В реальной жизни кандзи редко встречаются отдельно и в красивом обрамлении. Они приходят в потоке текста на сайте, в манге или в субтитрах, которые перегружают вашу рабочую память. Это происходит, когда вы стоите в движущемся поезде, одновременно слушая объявление, разговаривая со своим японским коллегой и просматривая что-то в своем телефоне. В такие моменты нередко бывает невозможно вспомнить даже иероглифы, которые вы знаете в совершенстве, просто из-за информационной и сенсорной перегрузки. </p>
<p>Тут вопрос не просто знаний, но навыка их применения, поэтому запаситесь достаточным количеством материала, который вы любите изучать, неважно что это, тексты песен, аниме, манга или статьи в интернете. Подходит все что угодно, главное чтобы была мотивация разбирать этот контент!</p>

<h5>Итак, позвольте мне оставить вас с двумя вещами.</h5>

<p>Первая - это представление о том, что вам не нужно изучать все кандзи джойо сразу. Японцы этого не делают. Они изучают около тысячи в начальной школе, но они изучают их через все 3 этапа. Имея примерно 1200 наиболее часто используемых иероглифов, вы можете легко (да, да не легко, но приемлимо) сформировать более 10000 самых важных слов языка и начать использовать их осмысленно.</p>
<p>Во-вторых, обучение чтению по-японски на самом деле является более масштабным проектом, чем может показаться на первый взгляд. Возможно, вы сможете выучить беглые значения всех иероглифов джойо за несколько месяцев, но научиться читать - это отдельная проблема. Приятно знать, во что ты ввязываешься.</p>
"""

doc__project__title = """Проект"""

doc__project__html = """
<p>Мунспик это рабочее место с набором из многих инструментов, которые очень удобны для изучения кандзи.</p>
<p>Открытый доступ начнется с 20 июля. В планах:</p>
<ul>
    <li>Расширение для браузера, показывающее личные мнемоники для кандзи</li>
    <li>Автоматическое создание карточек с иероглифами/словами по субтитрам к аниме.</li>
    <li>Онлайн клавиатура для печати на лунном</li>
</ul>
"""

doc__dev__title = """Разработка"""
doc__dev__html = """
<p>Сервис построен на микросервисной архитектуре, каждый бекенд компонент поставляется со своим фронтом, которые интегрируются через iframe на уровне браузера.</p>

<p>Для запуска локально используется docker-compose.yaml файл с описанием всех сервисов.</p>

<code>
    $ git clone https://github.com/temach/jplang/ && cd jplang && docker-compose up 
</code>

<p>Также надо добавить запись в /etc/hosts чтобы направить moonspeak.test на адрес 0.0.0.0</p>

<code>
    $ cat /etc/hosts
    # Static table lookup for hostnames.
    # See hosts(5) for details.
    127.0.0.1	localhost

    # moonspeak test environment 
    127.0.0.1	moonspeak.test
</code>

<p>Наконец можно сделать запрос в браузере на <a class="link link--light" href="http://moonspeak.test" target="_blank"><code>http://moonspeak.test</code></a></p>
"""


doc__feedback__title = """Обратная связь"""
doc__feedback__html = """
<p>Вступайте в телеграм канал <a class="link link--light" href="https://t.me/moonspeak_ru" target="_blank">@moonspeak_ru</a>, чтобы голосовать за фичи, общаться в чате, сообщать о проблемах и пожеланиях.</p>
<p>Также о проблеммах можно сообщить на <a class="link link--light" href="https://github.com/temach/jplang" target="_blank">Github</a>.</p>
"""

footer = """
Мунспик это открытый проект, участвуй в его разработке на <a class="link link--light" href="https://github.com/temach/jplang" target="_blank">Github</a>.
"""
