loading = "Loading..."
error = "Error"
error_getting_suggestions = "Error getting keyword suggestions for ${kanji}"
suggestions_are_empty = "No keyword suggestions found for this kanji: ${kanji}"
title = "Suggestions"
google_corpus_freq = "Corpus"
subtitles_freq = "Subtitles"
