lang = "ru"
title = "Доска"
loading_placeholder = """Загружаемся... если возникнут проблемы, сообщите нам!"""
contact_html = """
<ul>
    <li>
        Сообщите через <a href="https://github.com/temach/jplang" title="Github" target="_blank">Github</a> 
    </li>
    <li>
        Напишите комментарий в нашем телеграм канале <a href="https://t.me/moonspeak_ru" title="Moonspeak" target="_blank">@moonspeak_ru</a>
    </li>
</ul>
"""
