no_kanji = "X"
error = "Error"
unknown_error_description = "An error occurred"
http_error_timeout = "Server is taking too long to respond. Please try again later."
http_error_network = "Unable to reach server."
http_error_bad_status = "Request failed with status code: "
submit_failed = "Error submitting keyword. Details:"
submit_onclick_error = "Error: keyword length must be non-zero"
error_keyword_check = "Error getting keyword frequency"
keyword_placeholder = "Keyword"
google_corpus_freq = "Corpus:"
subtitles_freq = "Subs:"
submit_button = "Submit"
notes_title = "Notes"
title = "Work Elements"
