no_kanji = "X"
error = "Ошибка"
unknown_error_description = "Произошла ошибка"
http_error_timeout = "Сервер долго не отвечает, проверьте интернет соединение и повторите действие чуть позже."
http_error_network = "Нет подключения к серверу."
http_error_bad_status = "Действие завершилось с ошибкой: "
submit_failed = "Не могу сохранить слово. Ошибка:"
submit_onclick_error = "Ошибка: Ключевое слово слишком короткое"
error_keyword_check = "Не могу узнать частоту этого слова"
keyword_placeholder = "Ключевое слово"
total_freq = "Индекс слова: "
freq_decomposition_title = "Как считается индекс"
freq_decomposition_explanation = "Индекс с 1 по 1000 значит что слово очень популярно, чем больше индекс тем более редкое слово."
google_corpus_freq = "Индекс слова по интернету:"
subtitles_freq = "Индекс слова по субтитрам:"
submit_button = "Сохранить"
notes_title = "Заметки"
title = "Иероглифы"
