no_kanji = "X"
error = "Ошибка"
unknown_error_description = "Произошла ошибка"
http_error_timeout = "Сервер долго не отвечает, проверьте интернет соединение и повторите действие чуть позже."
http_error_network = "Нет подключения к серверу."
http_error_bad_status = "Действие завершилось с ошибкой: "
submit_failed = "Не могу сохранить слово. Ошибка:"
submit_onclick_error = "Ошибка: Ключевое слово слишком короткое"
error_keyword_check = "Не могу узнать частоту этого слова"
keyword_placeholder = "Ключевое слово"
google_corpus_freq = "Интернет:"
subtitles_freq = "Субтитры:"
submit_button = "Сохранить"
notes_title = "Заметки"
title = "Иероглифы"
