loading_placeholder = "loading..."
error_getting_synonyms = "Error getting synonyms from thesaurus"
error = "Error"
title = "Synonyms"
google_corpus_freq = "Internet corpus index"
subtitles_freq = "Subtitles corpus index"
total_freq = "Rarity"
freq_decomposition_title = "Word rarity score"
freq_decomposition_explanation = "Its best to use exotic and absurd words, they make the best mnemonics!"
keyword_placeholder = "enter keyword..."
popularity_column = "Similarity"
popularity_popover_title = "Synonym similarity"
popularity_popover_explanation = "Words that are closer synonyms appear closer to the top."
