loading_placeholder = "Загружаемся..."
error = "Ошибка"
error_getting_synonyms = "Ошибка: невозможно запросить синонимы из словаря"
title = "Синонимы"
google_corpus_freq = "Индекс слова по интернету"
subtitles_freq = "Индекс слова по субтитрам"
total_freq = "Редкость"
freq_decomposition_title = "Оценка редкости слова"
freq_decomposition_explanation = "Лучше всего использовать экзотические и абсурдные слова, их легче всего запомнить!"
keyword_placeholder = "введите слово..."
popularity_column = "Сходство"
popularity_popover_title = "Сходство синонимов"
popularity_popover_explanation = "Слова, которые являются более близкими синонимами, отображаются ближе к началу."
