lang = "ru"
title = """Moonspeak - победим иероглифы"""
menu__item__kanji = """Иероглифы"""
menu__item__documentation = """Документация"""

hero__title = """Moonspeak"""
hero__description = """
Победа над иероглифами!
"""

start_callout = "Без регистрации"
start_callout_button = "Старт &#8594;"

feature_title_1 = "Собственный список кандзи"
feature_html_1 = "Загрузи субтитры или текст книги, чтобы постепенно пополнять свой список иероглифов"

feature_title_2 = "Фразы мнемоники"
feature_html_2 = "Поможем сочинить вашу фразу мнемонику для каждого иероглифа"

feature_title_3 = "Личные границы"
feature_html_3 = "Не требуем ни почты, ни телефона"

feature_title_4 = "Без регистрации, без паролей"
feature_html_4 = "Выдаем уникальную ссылку с которой ты можешь зайти с любого устройства, держи ее в секрете"

feature_title_5 = "Многояз"
feature_html_5 = "Словари, синонимы и выражения с иероглифами сразу на нескольких языках"

feature_title_6 = "Открытый исходный код"
feature_html_6 = """Это открытый проект, участвуй в его развитии на <a class="link link--light" href="https://github.com/temach/jplang" title="Github" target="_blank">Github</a>"""

dev__title = "Разработчикам"

doc_callout = "Факты о кандзи и проекте, а также тех. документация проекта"
doc_callout_button = "Доки &#8594;"

changelog__title = "Изменения"

changelog__detail_1 = "Лендинг"
changelog__detail_2 = "Открылось тестирование"

changelog__callout_button = "История изменений"

footer_html = """
Мунспик это открытый проект, участвуй в его разработке на <a class="link link--light" href="https://github.com/temach/jplang" title="Github" target="_blank">Github</a>.
"""
