lang = "ru"
title = """Moonspeak - победим иероглифы"""
menu__item__index_html = """Главная"""
menu__item__documentation = """Документация"""
hero__title = """Скоро полноценный запуск!"""

hero__description_html = """
Сейчас мунспик в закрытом тестировании, подписывайтесь на телеграм канал чтобы узнать о запуске <a class="link link--light" href="https://t.me/MoonspeakRu" title="Moonspeak" target="_blank">@MoonspeakRu</a>
"""

footer_html = """
Мунспик это открытый проект, участвуй в его разработке на <a class="link link--light" href="https://github.com/temach/jplang" title="Github" target="_blank">Github</a>.
"""
