---
# These tasks create a deployment for single user 

- name: Create a busybox service
  community.docker.docker_container:
    state: started
    name: mydata
    image: busybox
    volumes:
      - /data
