lang = "ru"
title = "Moonspeak Документация"
logo_html = """Moonspeak <span class="logo__thin">Доки</span>"""
menu__item__index_html = """Главная"""

doc__nav__intro = "Введение"
doc__nav__project = "Проект"
doc__nav__dev = "Разработка"
doc__nav__feedback = "Обратная связь"

doc__introduction__title = """Введение"""
doc__introduction__html = """
<h5>Итак, вы решили выучить кандзи.</h5>

<p>Прекрасно, но прежде чем вы вступите в ряды людей, посвятивших свою жизнь изучению этого необычного языка, будет полезно рассмотреть, какие этапы вам предстоит преодолеть.</p>

<h5>Этап 1: Вы выучите отдельные иероглифы</h5>

<p>Иероглифов джойо <a class="link link--light" href="https://ru.wikipedia.org/wiki/%D0%94%D0%B7%D1%91%D1%91_%D0%BA%D0%B0%D0%BD%D0%B4%D0%B7%D0%B8" title="Wikiepdia" target="_blank"> всего 2136 </a>, звучит пугающе, не так ли? На протяжении многих лет люди предлагали разные способы их изучения. Кто-то использует метод Хейзига и учит только значение слова, без написания. Кто-то учит иероглифы сразу в контексте. Кому-то удобно придумывать мнемонику,  кому-то задействовать ассоциации с забавными картинками или разбирать их на составные части. Методов много, и только вам решать, какой использовать.</p>

<h5>Этап 2: Вы выучите сложные иероглифы и слова</h5>

<p>Отдельные иероглифы не очень полезны. Они приобретают значение в тот момент, когда вы начинаете создавать с их помощью слова и предложения. Примерно тогда же японская система письма начинает казаться либо бесконечно увлекательной, либо просто глупой, в зависимости от того, как вы на это смотрите. Например, 天 означает “небеса”, а 気 - “дух”. Если сложить их вместе, получается слово “погода”. Непросто догадаться, что небеса + дух = погода, но, по крайней мере, этому можно придумать объяснение, пусть и с натяжкой.</p>
<p>К сожалению, многое в японском еще более непонятно. Давайте рассмотрим один пример: иероглиф 気 значит “дух” + 象, что означает “слон” или “феномен”. Так что же значит 気象? Подсказка: это не дух мертвого слона. В этом вся проблема. </p>
<p>Даже если вы в совершенстве знаете все 2136 иероглифов, вы все равно не сможете читать по-японски. Чтение японского языка требует не только знания каждого из иероглифов, но также и четкого понимания того, как их использовать вместе для создания слов, а число этих слов исчисляется десятками тысяч. То есть, это более серьезная проблема, чем может показаться на первый взгляд.</p>

<h5>Этап 3: Вы будете читать в контексте. </h5>

<p>Теперь позвольте мне бросить вам еще один вызов. (О, и, кстати, 気象 также означает "погода”. Не спрашивайте почему.) Последняя задача - чтение иероглифов в контексте. В реальной жизни кандзи редко встречаются отдельно и в удобном виде. Они приходят в виде субтитров в аниме, в виде текста на новостном сайте или во время общения с японским коллегой. В такие моменты нередко бывает невозможно вспомнить даже те иероглифы, которые вы знаете в совершенстве, просто из-за информационной и сенсорной перегрузки. </p>
<p>Тут вопрос не только знаний, но и навыка их применения, поэтому запаситесь достаточным количеством материала, который вы любите изучать, неважно что это, тексты песен, аниме, манга или статьи в интернете. Подходит все что угодно, главное - ваша мотивация!</p>

<h5>Что ж, позвольте мне оставить вас с двумя вещами.</h5>

<p>Первая - понимание того, что вам не нужно изучать все кандзи джойо сразу. Японцы этого не делают. Они изучают около тысячи в начальной школе, но они изучают их через все 3 этапа. Имея примерно 1200 наиболее часто используемых иероглифов, вы можете легко (пусть не легко, но приемлимо) сформировать более 10000 самых важных слов языка и начать использовать их осмысленно.</p>
<p>Вторая, обучение чтению по-японски на самом деле является более масштабным проектом, чем может показаться на первый взгляд. Возможно, вы сможете выучить беглые значения всех иероглифов джойо за несколько месяцев, но научиться читать - это отдельная проблема. Приятно знать, во что ты ввязываешься.</p>
"""

doc__project__title = """Проект"""

doc__project__html = """
<p>Мунспик это рабочее место с набором инструментов, которые очень удобны для изучения кандзи.</p>
<p>Открытый доступ начнется 20 июля. В планах:</p>
<ul>
    <li>Расширение для браузера, показывающее личные мнемоники для кандзи</li>
    <li>Автоматическое создание карточек с иероглифами/словами по субтитрам к аниме.</li>
    <li>Онлайн клавиатура для печати на лунном</li>
</ul>
"""

doc__dev__title = """Разработка"""
doc__dev__html = """
<p>Сервис построен на микросервисной архитектуре, каждый бекенд компонент поставляется со своим фронтом, которые интегрируются через iframe на уровне браузера.</p>

<p>Для запуска локально используется docker-compose.yaml файл с описанием всех сервисов.</p>

<div class="code__block code__block--notabs">
    <pre class="code code--block">
        <code>
            $ git clone https://github.com/temach/jplang/ && cd jplang && docker-compose up
        </code>
    </pre>
</div>

<p>Также надо добавить запись в /etc/hosts чтобы направить moonspeak.test на адрес 0.0.0.0</p>

<div class="code__block code__block--notabs">
    <pre class="code code--block">
        <code>
            $ cat /etc/hosts
            # Static table lookup for hostnames.
            # See hosts(5) for details.
            127.0.0.1    localhost

            # moonspeak test environment
            127.0.0.1    moonspeak.test
        </code>
    </pre>
</div>

<p>Наконец можно сделать запрос в браузере на <a class="link link--light" href="http://moonspeak.test" title="Moonspeak" target="_blank"><code>http://moonspeak.test</code></a></p>
"""


doc__feedback__title = """Обратная связь"""
doc__feedback__html = """
<p>Вступайте в телеграм канал <a class="link link--light" href="https://t.me/moonspeak_ru" title="Moonspeak" target="_blank">@moonspeak_ru</a>, чтобы голосовать за фичи, общаться в чате, сообщать о проблемах и пожеланиях.</p>
<p>Также о проблемах можно сообщить на <a class="link link--light" href="https://github.com/temach/jplang" title="Github" target="_blank">Github</a>.</p>
"""

footer_html = """
Мунспик это открытый проект, участвуй в его разработке на <a class="link link--light" href="https://github.com/temach/jplang" title="Github" target="_blank">Github</a>.
"""
